name: {{ .Values.name | trunc 32 }}

static_sites:
  - name: web
    github:
      deploy_on_push: false
      branch: {{ requiredEnv "CI_REF_NAME" }}
      repo: renehernandez/review-apps-in-app-platform
    dockerfile_path: Dockerfile.static
    output_dir: /app/public
    envs:
      - key: REVIEW_ENVIRONMENT
        value: {{ .Values.envs.review_environment | quote }}
