name: {{ .Values.name | trunc 32 }}

static_sites:
- build_command: bundle exec jekyll build -d ./public
  environment_slug: jekyll
  github:
    deploy_on_push: false
    branch: {{ requiredEnv "CI_REF_NAME" }}
    repo: renehernandez/review-apps-in-app-platform
  name: sample-jekyll
  envs:
  - key: JEKYLL_ENV
    value: {{ .Values.envs.jekyll_env | quote }}
